# Introduction to NumPy


The learning objectives of this section are:

* Understand advantages of vectorised code using NumPy (over standard python ways)
* Create NumPy arrays
    * Convert lists and tuples to NumPy arrays 
    * Create (initialise) arrays
* Inspect the structure and content of arrays
* Subset, slice, index and iterate through arrays
* Compare computation times in NumPy and standard Python lists

### NumPy Basics

NumPy is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```ndarray```, or simply an ```array```, which is an **n-dimensional, homogenous** array. By homogenous, we mean that all the elements in a NumPy array have to be of the **same data type**, which is commonly numeric (float or integer). 

Let's see some examples of arrays.

In [1]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

In [4]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
array_1d = np.array([2, 4, 5, 6, 7, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [7]:
# this takes tuple also as input
array_1d = np.array((1,2,3,4,5,6,7))
print(array_1d)
print(type(array_1d))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [12]:
# creating a 2 dimentional array 
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)

array_2dt = np.array(((1,2,3,4),(5,6,7,8)))
print(array_2dt)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In NumPy, dimensions are called **axes**. In the 2-d array above, there are two axes, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

<img src="numpy_axes.jpg" style="width: 600px; height: 400px">

In [15]:
#Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]
list_1 = [1,2,3]
list_2 = [4,5,6]
list_3 = [7,8,9]

array_3d = np.array([list_1,list_2,list_3])
print(type(array_3d),array_3d)


<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Advantages of NumPy
- What is the use of arrays over lists, specifically for data analysis? Putting crudely, it is convenience and speed :
- You can write vectorised code on NumPy arrays, not on lists, which is convenient to read and write, and concise.
- NumPy is much faster than the standard Python ways to do computations.
- Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Say you have two lists of numbers, and want to calculate the element-wise product. The standard python list way would need you to map a lambda function (or worse - write a ```for``` loop), whereas with NumPy, you simply multiply the arrays.

In [16]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

multiple_list = list(map(lambda x,y: x*y, list_1,list_2))
print(multiple_list)

[12, 30, 7, 35]


In [20]:
# The numpy array way to do it: simply multiply the two arrays
array_list1=np.array(list_1)
array_list2=np.array(list_2)
array_product= array_list1*array_list2
print(list(array_product))

[12, 30, 7, 35]


As you can see, the NumPy way is clearly more concise.

Even simple mathematical operations on lists require for loops, unlike with arrays. For example, to calculate the square of every number in a list:

In [22]:
# square the array 
square_list = [x**2 for x in [2,4,5,6,7]]
print(square_list)

[4, 16, 25, 36, 49]


In [26]:
#in case of numpy ,it is relatively easy 
print(np.array([2,4,5,6,7])**2)

[ 4 16 25 36 49]


In [30]:
#Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 
list_1 = [2,3,4,5]
list_2 = [7,8,9,6]
list_3 = list(np.array(list_1)*np.array(list_2))
print(list_3)

[14, 24, 36, 30]


This was with 1-D arrays. You'll often work with 2-D arrays (matrices), where the difference would be even greater. With lists, you'll have to store matrices as lists of lists and loop through them. With NumPy, you simply multiply the matrices.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 

In [31]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


The other common way is to initialise arrays. You do this when you know the size of the array beforehand.

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [34]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=np.int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
   

In [38]:
# it will be 5 X 3 Array
array_ones = np.ones((5,3))
print(array_ones)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [42]:
#nothing changed with brackets
array_ones = np.ones([5,3], dtype = np.int)
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [41]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

array([0, 0, 0, 0])

In [44]:
# Creating array of zeros
np.zeros((4,3), dtype = np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
# Array of random numbers , a random method is explicitly need to be called
np.random.random([3, 4])

array([[ 0.33558963,  0.63355654,  0.84811886,  0.55844993],
       [ 0.287959  ,  0.03575964,  0.42467013,  0.68588778],
       [ 0.91697128,  0.92277345,  0.47458033,  0.60308878]])

In [46]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

In [47]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [48]:
# print odd numbers
number_odd = np.arange(1, 100, 2)
print(number_odd)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [52]:
# np.linspace()
# Sometimes, you know the length of the array, not the step size

# Array of length 25 between 15 and 18
np.linspace(15, 18, 25)

array([ 15.   ,  15.125,  15.25 ,  15.375,  15.5  ,  15.625,  15.75 ,
        15.875,  16.   ,  16.125,  16.25 ,  16.375,  16.5  ,  16.625,
        16.75 ,  16.875,  17.   ,  17.125,  17.25 ,  17.375,  17.5  ,
        17.625,  17.75 ,  17.875,  18.   ])

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [53]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [54]:
np.full(4, 7)

array([7, 7, 7, 7])

In [55]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [59]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, (3,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [60]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [63]:
# Create a 4 x 4 random array of integers ranging from 0 to 9(10-1)
np.random.randint(0, 10, (4,4))

array([[7, 9, 2, 6],
       [2, 7, 4, 7],
       [2, 4, 8, 5],
       [0, 9, 8, 2]])

In [64]:
#Given an integer 'x', create an array of size m*n having all integer values equal to 'x'. 
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [67]:
#Create an array of first 10 multiples of 5 using the 'arange' function.
np.arange(5,5*11,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [71]:
#Given an even integer ‘n’, create an ‘n*n’ checkerboard matrix with the values 0 and 1, using the tile function. 
input_num = int(int(input("Enter a number->"))/2)
array_default = np.array([[0,1],[1,0]])
np.tile(array_default, (input_num,input_num))

Enter a number->4


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

 ### Inspect the Structure and Content of Arrays

It is helpful to inspect the structure of numpy arrays, especially while working with large arrays. Some attributes of numpy arrays are:
* ```shape```: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes


Let's say you are working with a moderately large array of size 1000 x 300. First, you would want to wrap your head around the basic shape and size of the array. 

In [72]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the second row
print(rand_array[1, ])

[  1.15063511e-01   8.40523922e-01   7.48738399e-01   7.49298806e-01
   6.77478696e-01   9.15052340e-01   2.28120207e-01   3.02258937e-03
   7.63548864e-01   8.02896401e-01   5.65820650e-01   6.81944296e-01
   1.52636809e-01   8.00115510e-01   2.53978552e-01   6.30755800e-01
   5.90053562e-01   4.97428841e-01   4.04617103e-01   5.49766199e-01
   3.66731044e-01   4.49278419e-01   9.28931118e-01   8.50369386e-01
   3.84615396e-01   8.43442592e-01   3.64899220e-01   3.14784787e-02
   9.71169682e-01   9.95775969e-01   4.08439336e-01   3.78963049e-01
   2.83818432e-01   1.21318011e-01   7.53695190e-01   6.71984539e-01
   4.86776332e-01   1.49865950e-01   3.18575020e-01   7.90033202e-01
   1.36623764e-01   6.55029985e-01   8.06194323e-01   2.61187667e-01
   1.57175971e-01   1.93107803e-01   9.94674723e-01   5.61741148e-01
   5.57195703e-01   2.74559081e-01   7.00453238e-01   6.93269703e-01
   2.28248179e-01   2.57934037e-01   8.97310348e-01   3.93475093e-01
   9.43356439e-01   5.23142590e-01

In [73]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Item size: {}".format(rand_array.itemsize))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:
* The last axis is printed from left to right
* The second-to-last axis is printed from top to bottom
* The other axes are also printed top-to-bottom, with each slice separated by another using an empty line 

Let's see some examples.

In [75]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 3, 4)  # here 2 is the 
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


* The last axis has 4 elements, and is printed from left to right.
* The second last has 3, and is printed top to bottom
* The other axis has 2, and is printed in the two separated blocks

In [77]:
#Create an array using list list_1 = [10,11,12,13] and list_2 = [15,12,13,14] 
#and print the shape and dimension of the array created.
list_1 = [10,11,12,13]  
list_2 = [15,12,13,14] 

final_array = np.array([list_1,list_2])
print(final_array.shape)
print(final_array.ndim)
print(final_array.dtype)
print(final_array.itemsize)

(2, 4)
2
int64
8


### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

In [80]:
array_1d = np.arange(10)
print(array_1d)
array_rand = np.random.randint(0, 10, 10)
print(array_rand)

[0 1 2 3 4 5 6 7 8 9]
[5 0 5 1 0 7 9 7 0 2]


In [83]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])
print(array_rand[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 6]
[5 7 9]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [88]:
array_2d =np.arange(1,10).reshape(3, 3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
print(array_2d[:,1:2])

[[5]
 [8]]


In [82]:
#iterating over the array,it is similiar to list 
#ARRAY ARE NOT MEANT TO BE ITERATING , EXAM
for i in array_1d:
    print(i)

0
1
2
3
4
5
6
7
8
9


**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```. 

Each axes has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.

<img src="2_d_array.png" style="width: 350px; height: 300px">

In [98]:
# Creating a 2-D array
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [99]:
# Third row second column
print(array_2d[2, 1])

12


In [100]:
# Slicing the second row, and all columns
# Notice that the resultant is itself a 1-D array
print(array_2d[1, :])
print(type(array_2d[1, :]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [101]:
# Slicing all rows and the third column
print(array_2d[:, 2])

[ 7  8 15]


In [102]:
# Slicing all rows and the first three columns
print(array_2d[:, :3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


**Iterating on 2-D arrays** is done with respect to the first axis (which is row, the second axis is column). 

In [103]:
# Iterating over 2-D arrays
for row in array_2d:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [104]:
# Iterating over 3-D arrays: Done with respect to the first axis
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [105]:
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [107]:
#Extract all the border rows and columns from a 2-D array.
array_4 = np.array([[11, 12, 13, 14],
 [21, 22, 23, 24],
 [31, 32, 33, 34]])
print(array_4)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [115]:
print(array_4[:,0])
print(array_4[0,:])
print(array_4[:,3])
print(array_4[2,:])

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


### Compare Computation Times in NumPy and Standard Python Lists

We mentioned that the key advantages of numpy are convenience and speed of computation. 

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.   

Let's compare the computation times of arrays and lists for a simple task of calculating the element-wise product of numbers. 

- NumPy is an order of magnitude faster than lists.

In [116]:
## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)


# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))

0.17221593856811523
0.0066602230072021484
The ratio of time taken is 25.857383211025596


In this case, numpy is **an order of magnitude faster** than lists. This is with arrays of size in millions, but you may work on much larger arrays of sizes in order of billions. Then, the difference is even larger.

Some reasons for such difference in speed are:
* NumPy is written in C, which is basically being executed behind the scenes
* NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists


The following discussions demonstrate the differences in speeds of NumPy and standard python:
1. https://stackoverflow.com/questions/8385602/why-are-numpy-arrays-so-fast
2. https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists

# Operations on NumPy Arrays

The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 

### Manipulating Arrays

Let's look at some ways to manipulate arrays, i.e. changing the shape, combining and splitting arrays, etc.   

#### Reshaping Arrays

Reshaping is done using the ```reshape()``` function.



In [117]:
# Reshape a 1-D array to a 3 x 4 array
some_array = np.arange(0, 12).reshape(3, 4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [118]:
# Can reshape it further 
some_array.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [119]:
# If you specify -1 as a dimension, the dimensions are automatically calculated
# -1 means "whatever dimension is needed" 
some_array.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [120]:
# If you specify -1 as a dimension, the dimensions are automatically calculated
# -1 means "whatever dimension is needed" 
some_array.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

```array.T``` returns the transpose of an array.

In [121]:
some_array.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Stacking and Splitting Arrays

#### Stacking: ```np.hstack()``` and ```n.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

In [122]:
# Creating two arrays
array_1 = np.arange(12).reshape(3, 4)
array_2 = np.arange(20).reshape(5, 4)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [123]:
# vstack
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list
np.vstack((array_1, array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Similarly, two arrays having the same number of rows can be horizontally stacked using ```np.hstack((a, b))```.

In [124]:
# Creating two arrays
array_1 = np.arange(12).reshape(4, -1)
array_2 = np.arange(20).reshape(4, -1)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [138]:
np.hstack((array_1,array_2))

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19]])

In [143]:
input_list= [[[1, 2], [5, 6]], [[3, 4], [7, 8]], [[9, 10, 11, 12]]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]
list_hstack = np.hstack((np.array(list_1),np.array(list_2)))
print(list_hstack)

list_vstack = np.vstack((list_hstack,np.array(list_3)))
print(list_vstack)


[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Perform Operations on Arrays

Performing mathematical operations on arrays is extremely simple. Let's see some common operations.


#### Basic Mathematical Operations

NumPy provides almost all the basic math functions - exp, sin, cos, log, sqrt etc. The function is applied to each element of the array.

In [126]:
# Basic mathematical operations
a = np.arange(1, 20)

# sin, cos, exp, log
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
[  2.71828183e+00   7.38905610e+00   2.00855369e+01   5.45981500e+01
   1.48413159e+02   4.03428793e+02   1.09663316e+03   2.98095799e+03
   8.10308393e+03   2.20264658e+04   5.98741417e+04   1.62754791e+05
   4.42413392e+05   1.20260428e+06   3.26901737e+06   8.88611052e+06
   2.41549528e+07   6.56599691e+07   1.78482301e+08]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791  1.79175947
  1.94591015  2.07944154  2.19722458  2.30258509  2.39789527  2.48490665
  2.56494936  2.63905733  2.7080502   2.77258872  2.83321334

#### Apply User Defined Functions

You can also apply your own functions on arrays. For e.g. applying the function ```x/(x+1)``` to each element of an array.

One way to do that is by looping through the array, which is the non-numpy way. You would rather want to write **vectorised code**. 

The simplest way to do that is to vectorise the function you want, and then apply it on the array. Numpy provides the ```np.vectorize()``` method to vectorise functions.

Let's look at both the ways to do it.

In [127]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [128]:
# The non-numpy way, not recommended
a_list = [x/(x+1) for x in a]
print(a_list)

[0.5, 0.66666666666666663, 0.75, 0.80000000000000004, 0.83333333333333337, 0.8571428571428571, 0.875, 0.88888888888888884, 0.90000000000000002, 0.90909090909090906, 0.91666666666666663, 0.92307692307692313, 0.9285714285714286, 0.93333333333333335, 0.9375, 0.94117647058823528, 0.94444444444444442, 0.94736842105263153, 0.94999999999999996]


In [129]:
# The numpy way: vectorize the function, then apply it
f = np.vectorize(lambda x: x/(x+1))
f(a)

array([ 0.5       ,  0.66666667,  0.75      ,  0.8       ,  0.83333333,
        0.85714286,  0.875     ,  0.88888889,  0.9       ,  0.90909091,
        0.91666667,  0.92307692,  0.92857143,  0.93333333,  0.9375    ,
        0.94117647,  0.94444444,  0.94736842,  0.95      ])

In [130]:
# Apply function on a 2-d array: Applied to each element 
b = np.linspace(1, 100, 10)
f(b)

array([ 0.5       ,  0.92307692,  0.95833333,  0.97142857,  0.97826087,
        0.98245614,  0.98529412,  0.98734177,  0.98888889,  0.99009901])

This also has the advantage that you can vectorize the function once, and then apply it as many times as needed. 

#### Apply Basic Linear Algebra Operations

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 



In [131]:
# np.linalg documentation
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

In [132]:
# Creating arrays
a = np.arange(1, 10).reshape(3, 3)
b= np.arange(1, 13).reshape(3, 4)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [133]:
# Inverse
np.linalg.inv(a)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [134]:
# Determinant
np.linalg.det(a)

-9.5161973539299405e-16

In [135]:
# Eigenvalues and eigenvectors
np.linalg.eig(a)

(array([  1.61168440e+01,  -1.11684397e+00,  -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [137]:
# Multiply matrices IMPORTANT FOR EXAM
np.dot(a, b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

In [145]:
#Given an array, 'array_3' divide each element with 5. 
#Hint: Create a vectorized function, then apply it to the array_3.

array_3= np.array([[1,2,3,4],[4,7,5,6],[9,0,7,8],[6,7,8,5]])
fun = np.vectorize(lambda x: x/5)
fun(array_3)

array([[ 0.2,  0.4,  0.6,  0.8],
       [ 0.8,  1.4,  1. ,  1.2],
       [ 1.8,  0. ,  1.4,  1.6],
       [ 1.2,  1.4,  1.6,  1. ]])